name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build 

      - name: Add .nojekyll to dist
        run: echo > ./dist/.nojekyll

      - name: Show dist contents
        run: |
          echo "Working directory:"
          pwd
          echo "Files in ./dist:"
          ls -la ./dist

      - name: Show encrypt-mode1 contents
        run: |
          echo "encrypt-mode1.html contents:"
          cat encrypt-mode1.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_GITHUB_TOKEN }}
          publish_dir: ./dist
